export enum TAGS {
  "All Genres" = " ",
  MMORPG = "mmorpg",
  Shooter = "shooter",
  strategy = "strategy",
  MOBA = "moba",
  Racing = "racing",
  Sport = "sports",
  Social = "social",
  Sandbox = "sandbox",
  "Open World" = "open-world",
  Servival = "survival",
  PVP = "pvp",
  PVE = "pve",
  Pixel = "pixel",
  Voxel = "voxel",
  Zombie = "zombie",
  TurnBased = "turn-based",
  "First Person" = "first-person",
  "Third Person" = "third-Person",
  TopDown = "top-down",
  Tank = "tank",
  Space = "space",
  Sailing = "sailing",
  SideScroller = "side-scroller",
  Superhero = "superhero",
  Permadeath = "permadeath",
  Cadr = "card",
  "Battle Royale" = "battle-royale",
  MMO = "mmo",
  MMPFPS = "mmofps",
  "3D" = "3d",
  "2D" = "2d",
  Anime = "anime",
  Fantasy = "fantasy",
  SciFi = "sci-fi",
  Fighting = "fighting",
  ActionRPG = "action-rpg",
  Action = "action",
  Military = "military",
  "Material Arts" = "martial-arts",
  Flight = "flight",
  LowSpec = "low-spec",
  "Tower Defence" = "tower-defense",
  Horror = "horror",
  MMORTS = "mmorts",
}

export enum SORT {
  'Release Date' = "release-date",
  Popularity = "popularity",
  Alphabetical = "alphabetical",
  Relevance = "relevance",
}

export enum PLATFORMS {
  PC = "pc",
  Browser = "browser",
  'All Platforms' = "all",
}
